application: jin-nang
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /html
  static_dir: html/
- url: /css
  static_dir: css/
- url: /images
  static_dir: images/
- url: /js
  static_dir: js/
- url: /.*
  script: main.py