application: jin-nang
version: 3
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/x-icon

- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /.*
  script: main.py